// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Deudoresv3.Data.Sql
{
    public partial class Rdeudores
    {
        public long Rd { get; set; }
        public DateTime Rdfecreg { get; set; }
        public DateTime? Rdtimereg { get; set; }
        public DateTime? Rdtimefin { get; set; }
    }
}